// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD2fWzCuiIlA6DmDVZgqC15DgEEmDrL2c',
    appId: '1:496695234100:web:c0433da99f33c32d1a0461',
    messagingSenderId: '496695234100',
    projectId: 'proje-ce4a3',
    authDomain: 'proje-ce4a3.firebaseapp.com',
    storageBucket: 'proje-ce4a3.firebasestorage.app',
    measurementId: 'G-BFH4V5GGZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8o2mGptx26fpgffCReby8lAi7NgrTesk',
    appId: '1:496695234100:android:25970b262ee334cc1a0461',
    messagingSenderId: '496695234100',
    projectId: 'proje-ce4a3',
    storageBucket: 'proje-ce4a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1BAmZHn6h-3tS705BGussFLLQhxA8NWk',
    appId: '1:496695234100:ios:8881e8949813609e1a0461',
    messagingSenderId: '496695234100',
    projectId: 'proje-ce4a3',
    storageBucket: 'proje-ce4a3.firebasestorage.app',
    iosBundleId: 'com.uu.bookProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1BAmZHn6h-3tS705BGussFLLQhxA8NWk',
    appId: '1:496695234100:ios:8881e8949813609e1a0461',
    messagingSenderId: '496695234100',
    projectId: 'proje-ce4a3',
    storageBucket: 'proje-ce4a3.firebasestorage.app',
    iosBundleId: 'com.uu.bookProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD2fWzCuiIlA6DmDVZgqC15DgEEmDrL2c',
    appId: '1:496695234100:web:e075eac77ff5a29d1a0461',
    messagingSenderId: '496695234100',
    projectId: 'proje-ce4a3',
    authDomain: 'proje-ce4a3.firebaseapp.com',
    storageBucket: 'proje-ce4a3.firebasestorage.app',
    measurementId: 'G-5YS69E63HZ',
  );
}
